@echo off
echo Setting up environment...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment and installing dependencies...
call venv\Scripts\activate
pip install -r requirements.txt
echo Starting server...
uvicorn app.main:app --reload
pause
